### ISSUE TITLE
EPICS waveform strings should be text

### ISSUE THREAD

**Issue by prjemian** [prjemian/pvWebMonitor#19]
Could you fix the python code to reading strings that are in waveform records, it needs "asString=True" option to be defined?

**Comment by prjemian** [comment]
@sureshnAPS, the plan is to add an attribute to entries in the pvlist.xml file

```
as_string="true"
```

The default is "false", if true, this code will retrieve the PV value from EPICS:

```
value = pv.get(as_string=True)
```

else:

```
value = pv.get()
```

Is that what you had in mind?

**Comment by sureshnaps** [comment]
Pete, that would be perfect.

**Comment by sureshnaps** [comment]
```
Pete,

Yes, this would be perfect.
I responded in git as well.

Suresh


On 09/06/2016 05:34 PM, Pete R Jemian
  wrote:



  @sureshnAPS, the plan is to add an
    attribute to entries in the pvlist.xml file
  as_string="true"

  The default is "false", if true, this code will retrieve the PV
    value from EPICS:
  value = pv.get(as_string=True)

  else:
  value = pv.get()

  Is that what you had in mind?
  —
    You are receiving this because you were mentioned.
    Reply to this email directly, view
      it on GitHub, or mute
      the thread.










  {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/prjemian/pvWebMonitor","title":"prjemian/pvWebMonitor","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/prjemian/pvWebMonitor"}},"updates":{"snippets":[{"icon":"PERSON","message":"@prjemian in #19: @sureshnAPS, the plan is to add an attribute to entries in the pvlist.xml file\r\n\r\n    as_string=\"true\"\r\n\r\nThe default is \"false\", if true, this code will retrieve the PV value from EPICS:\r\n\r\n    value = pv.get(as_string=True)\r\n\r\nelse:\r\n\r\n    value = pv.get()\r\n\r\nIs that what you had in mind?"}],"act
```

ion":{"name":"View Issue","url":"https://github.com/prjemian/pvWebMonitor/issues/19#issuecomment-245117421"}}}

**Comment by sureshnaps** [comment]
does this mean, this is fixed?

**Comment by prjemian** [comment]
yes

the new version has been posted to APSshare and should appear for you 
tomorrow morning

It was tested before the issue was finalized

The docs need to be updated.

The as_string attribute is used to control the text that goes into the 
default value (the one commonly displayed) written to the rawdata.xml 
file.  Additionally, the raw_value and the char_value are both available 
in the rawdata.xml file.

You won't be able to try the new version (2016.0907.0) until the IT 
maintenance on the web server is complete - hope we can try tomorrow.

Pete

**Comment by sureshnaps** [comment]
Great, looking forward to tomorrow.
