### ISSUE TITLE
pvWebMonitor not updating

### ISSUE THREAD

**Issue by prjemian** [prjemian/pvWebMonitor#24]
starts ok, nothing seems to happen and no updates, ALL PVs exist and are getting new CA monitors

```
pvWebMonitor starting
read configuration file: <the name>
configuration schema version: 1.0.1
```

**Comment by prjemian** [comment]
ran xmllint on both config.xml and pvlist.xml with no errors:

```
xmllint --noout --schema  /path/to/pvWebMonitor/config_1_0_1.xsd config.xml
xmllint --noout --schema  /path/to/pvWebMonitor/pvlist.xsd config.xml
```

**Comment by prjemian** [comment]
Could add a log message after pvlist.xml file validation

**Comment by prjemian** [comment]
@kurtgoetze:
It's waiting for the call to `epics.PV(pv)`  in `pvwatch.PvWatch.add_pv()` to return.  Hasn't waited here before.  Might need to apply a connection_timeout per the docs (http://cars9.uchicago.edu/software/python/pyepics3/pv.html#the-pv-class).

Might have to ask Matt @newville about this.  PyEpics v3.2.5 on RHEL6 linux using Anaconda.

**Comment by prjemian** [comment]
Definitely it is a problem in PyEpics, somehow.  Here is an ipython session:

```
 jemian@bakfark ~/.../src/pvWebMonitor $ /APSshare/anaconda/x86_64/bin/ipython
 import epics
 Python 2.7.11 |Anaconda 4.0.0 (64-bit)| (default, Dec  6 2015, 18:08:32)
 Type "copyright", "credits" or "license" for more information.

 IPython 4.1.2 -- An enhanced Interactive Python.
 ?         -> Introduction and overview of IPython's features.
 %quickref -> Quick reference.
 help      -> Python's own help system.
 object?   -> Details about 'object', use 'object??' for extra details.

 In [1]: import epics

 In [2]: epics.__version__
 Out[2]: '3.2.5'

 In [3]: v = epics.caget('1ida:AMI286:1:ch2:Level.VAL')
 ^C^C^Z^]
```

Note the ipython session was stalled after the IN[3] line.  Control C or other would not interrupt it.

The PV is available, though:

```
bakfark > caget 1ida:AMI286:1:ch2:Level.VAL
1ida:AMI286:1:ch2:Level.VAL    97
bakfark > caget 1ida:AMI286:1:ch2:Level.RTYP
1ida:AMI286:1:ch2:Level.RTYP   calc
bakfark > cainfo 1ida:AMI286:1:ch2:Level.VAL
1ida:AMI286:1:ch2:Level.VAL
    State:        connected
    Host:         ioc1ida.xray.aps.anl.gov:5064
    Access:       read, write
    Native data type: DBF_DOUBLE
    Request type:     DBR_DOUBLE
    Element count:    1
```

**Comment by prjemian** [comment]
Inside PyEpics pv.py at line 132, the debugger stalls on the line to `if ca.current_context() is None:`

**Comment by prjemian** [comment]
in ca.py, calls `load_dll()`  which ultimately fails in a call to `_dlopen()`

why?

**Comment by prjemian** [comment]
PyEpics was upgraded on /APSshare/anaconda to version 3.2.5 on 2016-05-25
That's the latest version according to the PyEpics web site: http://cars9.uchicago.edu/software/python/pyepics3

**Comment by prjemian** [comment]
Ipython test works correctly on the 32-bit Python installation: /APSshare/anaconda/x86/bin/ipython

try the 32-bit python with the pvWebMonitor tool

**Comment by prjemian** [comment]
Started using the x86 version of Python, lots of complaints in the log about `undefined symbol: PC` in libreadline.so.6

**Comment by prjemian** [comment]
Looks less like a problem with pvWebMonitor or PyEpics, more a problem with the EPICS libraries made available to PyEpics and their libreadline version dependence

**Comment by newville** [comment]
@prjemian  I think I have also seen trouble with anaconda on some Linux installs in which (I think) the libreadline.so that is included in the anaconda distribution is out-of-date with the system library. 

Typically, libca.so and libCom.so link to libreadline.so (though: why?), probably pointing to /lib64/libreadline.so.6, but Python has already loaded /home/USER/anaconda2/lib/libreadline.so.6 which is probably newer, or at least different. 

Maybe libca.so and libCom.so should be built for anaconda on linux, using its libraries, and then distributed as a conda package?   I haven't really thought about that in detail, but it might be best to think about binaries for linux.

But also: I don't understand is why libca.so and libCom.so load readline at all.  Maybe that's worth looking into too.

**Comment by prjemian** [comment]
Summary (@kurtgoetze @newville ):

the reported problem comes down  to libreadline6 not loading for the EPICS library libca

diagnosing form the command line, there are lower level problems in accessing and using the libca library from the specific host (bakfark)
Running the unmodified pvWebMonitor software (with unmodified PyEpics and Anaconda Python) is successful on a different computer on the same subnet.

Conclusion:

problem with the computer, not the software
